import { integer, sqliteTable, text, uniqueIndex, check } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';

export const users = sqliteTable('users', { id: text().primaryKey(), email: text().notNull().unique(), passwordHash: text('password_hash').notNull(), fullName: text('full_name').notNull(), role: text({ enum: ['murid', 'guru'] }).notNull(), isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true), createdAt: integer('created_at').notNull(), updatedAt: integer('updated_at').notNull() }, (table) => [check('users_role_check', sql`${table.role} in ('murid', 'guru')`)]);
export const studentProfiles = sqliteTable('student_profiles', { userId: text('user_id').primaryKey().references(() => users.id), nis: text().notNull().unique(), createdAt: integer('created_at').notNull(), updatedAt: integer('updated_at').notNull() });
export const teacherProfiles = sqliteTable('teacher_profiles', { userId: text('user_id').primaryKey().references(() => users.id), nip: text().unique(), isAdmin: integer('is_admin', { mode: 'boolean' }).notNull().default(false), createdAt: integer('created_at').notNull(), updatedAt: integer('updated_at').notNull() });
export const registrationCodes = sqliteTable('registration_codes', { code: text().primaryKey(), roleAllowed: text('role_allowed', { enum: ['murid', 'guru'] }).notNull(), isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true), maxUses: integer('max_uses'), usedCount: integer('used_count').notNull().default(0), expiresAt: integer('expires_at'), createdAt: integer('created_at').notNull(), updatedAt: integer('updated_at').notNull() }, (table) => [check('registration_codes_role_allowed_check', sql`${table.roleAllowed} in ('murid', 'guru')`)]);
export const devices = sqliteTable('devices', { id: integer().primaryKey({ autoIncrement: true }), userId: text('user_id').notNull().references(() => users.id), deviceId: text('device_id'), platform: text(), model: text(), userAgent: text('user_agent').notNull(), createdAt: integer('created_at').notNull(), updatedAt: integer('updated_at').notNull(), lastSeenAt: integer('last_seen_at').notNull() }, (table) => [uniqueIndex('devices_device_id_unique').on(table.deviceId)]);
export const refreshTokens = sqliteTable('refresh_tokens', { id: text().primaryKey(), userId: text('user_id').notNull().references(() => users.id), tokenHash: text('token_hash').notNull().unique(), familyId: text('family_id').notNull(), deviceId: integer('device_id').notNull().references(() => devices.id), expiresAt: integer('expires_at').notNull(), revokedAt: integer('revoked_at'), createdAt: integer('created_at').notNull() });
export const auditLogs = sqliteTable('audit_logs', { id: text().primaryKey(), userId: text('user_id').references(() => users.id), action: text().notNull(), metadata: text(), ip: text(), createdAt: integer('created_at').notNull() });
